export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';

export const LIKE_MOVIE = 'LIKE_MOVIE';
export const LIKE_MOVIE_SUCCESS = 'LIKE_MOVIE_SUCCESS';
export const LIKE_MOVIE_FAIL = 'LIKE_MOVIE_FAIL';

export default {
  FETCH_MOVIES,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAIL,
  LIKE_MOVIE,
  LIKE_MOVIE_SUCCESS,
  LIKE_MOVIE_FAIL,
};
