export const movies = [
  {
    vote_count: 17839,
    id: 24428,
    video: false,
    vote_average: 7.6,
    title: 'The Avengers',
    popularity: 47.408,
    poster_path: '/cezWGskPY5x7GaglTTRN4Fugfb8.jpg',
    original_language: 'en',
    original_title: 'The Avengers',
    genre_ids: [878, 28, 12],
    backdrop_path: '/hbn46fQaRmlpBuUrEiFqv0GDL6Y.jpg',
    adult: false,
    overview:
      'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
    release_date: '2012-04-25',
  },
  {
    vote_count: 11138,
    id: 299536,
    video: false,
    vote_average: 8.3,
    title: 'Avengers: Infinity War',
    popularity: 109.856,
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    original_language: 'en',
    original_title: 'Avengers: Infinity War',
    genre_ids: [12, 28, 14],
    backdrop_path: '/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg',
    adult: false,
    overview:
      'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    release_date: '2018-04-25',
  },
  {
    vote_count: 0,
    id: 299534,
    video: false,
    vote_average: 0,
    title: 'Avengers: Endgame',
    popularity: 33.795,
    poster_path: '/bJLYrLIHT1r7cikhWGbpZkxlUpA.jpg',
    original_language: 'en',
    original_title: 'Avengers: Endgame',
    genre_ids: [12, 878, 28],
    backdrop_path: '/aw8niyYZNTonD1ep5vMZm9LZ26Z.jpg',
    adult: false,
    overview:
      'A culmination of 22 interconnected films and the finale of this epic journey across the length and breadth of the Marvel Cinematic Universe.  Our beloved heroes will truly understand how fragile this reality is and the sacrifices that must be made to uphold it.',
    release_date: '2019-04-24',
  },
  {
    vote_count: 11948,
    id: 99861,
    video: false,
    vote_average: 7.3,
    title: 'Avengers: Age of Ultron',
    popularity: 33.106,
    poster_path: '/t90Y3G8UGQp0f0DrP60wRu9gfrH.jpg',
    original_language: 'en',
    original_title: 'Avengers: Age of Ultron',
    genre_ids: [28, 12, 878],
    backdrop_path: '/rFtsE7Lhlc2jRWF7SRAU0fvrveQ.jpg',
    adult: false,
    overview:
      'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
    release_date: '2015-04-22',
  },
  {
    vote_count: 308,
    id: 9320,
    video: false,
    vote_average: 4.3,
    title: 'The Avengers',
    popularity: 7.245,
    poster_path: '/zxjJ2IxhilZLzl8eXjj7S0apZ7k.jpg',
    original_language: 'en',
    original_title: 'The Avengers',
    genre_ids: [53, 878],
    backdrop_path: '/8YW4rwWQgC2JRlBcpStMNUko13k.jpg',
    adult: false,
    overview:
      'British Ministry agent John Steed, under direction from "Mother", investigates a diabolical plot by arch-villain Sir August de Wynter to rule the world with his weather control machine. Steed investigates the beautiful Doctor Mrs. Emma Peel, the only suspect, but simultaneously falls for her and joins forces with her to combat Sir August.',
    release_date: '1998-08-13',
  },
  {
    vote_count: 132,
    id: 14609,
    video: false,
    vote_average: 6.5,
    title: 'Ultimate Avengers',
    popularity: 7.206,
    poster_path: '/pmNYggLktcWHzQeCru5ywL4OiRH.jpg',
    original_language: 'en',
    original_title: 'Ultimate Avengers',
    genre_ids: [28, 16, 12, 878],
    backdrop_path: '/cXHiXZWTPMClrJazhi7ZaB7Y3iK.jpg',
    adult: false,
    overview:
      'When a nuclear missile was fired at Washington in 1945, Captain America managed to detonate it in the upper atmosphere. But then he fell miles into the icy depths of the North Atlantic, where he remained lost for over sixty years. But now, with the world facing the very same evil, Captain America must rise again as our last hope for survival.',
    release_date: '2006-02-21',
  },
  {
    vote_count: 112,
    id: 14611,
    video: false,
    vote_average: 6.3,
    title: 'Ultimate Avengers 2',
    popularity: 7.586,
    poster_path: '/u7vvexSU81Qk20yU7Vog23Ogob.jpg',
    original_language: 'en',
    original_title: 'Ultimate Avengers 2',
    genre_ids: [12, 16, 28, 878],
    backdrop_path: '/85NqI4WuCim6dZexmTPUAi13Af0.jpg',
    adult: false,
    overview:
      'Mysterious Wakanda lies in the darkest heart of Africa, unknown to most of the world. An isolated land hidden behind closed borders, fiercely protected by its young king - the Black Panther. But when brutal alien invaders attack, the threat leaves the Black Panther with no option but to go against the sacred decrees of his people and ask for help from outsiders.',
    release_date: '2006-08-08',
  },
];

export default movies;
